# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'project1CS691' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for project1CS691
 pod 'Firebase/Core'
 pod 'Firebase/Database'
 pod 'Firebase/Auth'
 pod 'Firebase/Storage'
 

  target 'project1CS691Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'project1CS691UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
