# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CS691Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CS691Project
 pod 'Firebase/Core'
pod 'Firebase/Database'
 pod 'Firebase/Auth'
 pod 'Firebase/Storage'

  target 'CS691ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CS691ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
